name: Pull Request Triage

on:
  pull_request_target:
    types:
      - opened

permissions:
  actions: read
  checks: read
  contents: read
  deployments: none
  issues: none
  packages: none
  pull-requests: read
  repository-projects: none
  security-events: none
  statuses: read

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@5682b7c5137476cceba78108d82b25ae7897cc7c
      with:
        configuration-path: .github/labeler-pull-request-triage.yml
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
    # See also: https://github.com/CodelyTV/pr-size-labeler/pull/26
    - uses: bflad/pr-size-labeler@7df62b12a176513631973abfe151d2b6213c3f12
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        xs_label: 'size/XS'
        xs_max_size: '30'
        s_label: 'size/S'
        s_max_size: '60'
        m_label: 'size/M'
        m_max_size: '150'
        l_label: 'size/L'
        l_max_size: '300'
        xl_label: 'size/XL'
        message_if_xl: ''
